language: go

go:
  - 1.14

os:
  - linux
  - osx
  - windows

cache:
  directories:
    - .build

before_script:
  - if [ "$TRAVIS_OS_NAME" = linux ]; then rmdir --ignore-fail-on-non-empty .build; fi

script:
  - if [ "$TRAVIS_OS_NAME" = linux ]; then make all GO_TEST_FLAGS='-coverprofile=coverage.txt'; fi
  - if [ "$TRAVIS_OS_NAME" = linux ]; then git diff --exit-code; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then go test ./...; fi
  - if [ "$TRAVIS_OS_NAME" = windows ]; then go test ./...; fi

after_success:
  - if [ "$TRAVIS_OS_NAME" = linux ]; then bash <(curl -s https://codecov.io/bash); fi
