language: go

go:
  - 1.14

os:
  - linux
  - osx
  - windows

cache:
  directories:
    - .build

before_script:
  - if [ "$TRAVIS_OS_NAME" = linux ]; then chown --recursive travis:travis .build && rmdir --ignore-fail-on-non-empty .build; fi

script:
  - >-
    if [ "$TRAVIS_OS_NAME" = linux ]; then make all
    POST_GENERATE='git diff --exit-code'
    POST_FMT='git diff --exit-code'
    GO_TEST_FLAGS='-race -coverprofile=coverage.txt'; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then go test ./...; fi
  - if [ "$TRAVIS_OS_NAME" = windows ]; then go test ./...; fi

after_success:
  - if [ "$TRAVIS_OS_NAME" = linux ]; then bash <(curl -s https://codecov.io/bash) -f coverage.txt -X fix; fi
